/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PengangkutanRouteImport } from './routes/pengangkutan'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as BinsRouteImport } from './routes/bins'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengangkutanRoute = PengangkutanRouteImport.update({
  id: '/pengangkutan',
  path: '/pengangkutan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsRoute = BinsRouteImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/laporan': typeof LaporanRoute
  '/monitoring': typeof MonitoringRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pengangkutan': typeof PengangkutanRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/laporan': typeof LaporanRoute
  '/monitoring': typeof MonitoringRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pengangkutan': typeof PengangkutanRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/laporan': typeof LaporanRoute
  '/monitoring': typeof MonitoringRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pengangkutan': typeof PengangkutanRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bins'
    | '/laporan'
    | '/monitoring'
    | '/notifikasi'
    | '/pengangkutan'
    | '/pengaturan'
    | '/riwayat'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bins'
    | '/laporan'
    | '/monitoring'
    | '/notifikasi'
    | '/pengangkutan'
    | '/pengaturan'
    | '/riwayat'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/bins'
    | '/laporan'
    | '/monitoring'
    | '/notifikasi'
    | '/pengangkutan'
    | '/pengaturan'
    | '/riwayat'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinsRoute: typeof BinsRoute
  LaporanRoute: typeof LaporanRoute
  MonitoringRoute: typeof MonitoringRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PengangkutanRoute: typeof PengangkutanRoute
  PengaturanRoute: typeof PengaturanRoute
  RiwayatRoute: typeof RiwayatRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengangkutan': {
      id: '/pengangkutan'
      path: '/pengangkutan'
      fullPath: '/pengangkutan'
      preLoaderRoute: typeof PengangkutanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins': {
      id: '/bins'
      path: '/bins'
      fullPath: '/bins'
      preLoaderRoute: typeof BinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinsRoute: BinsRoute,
  LaporanRoute: LaporanRoute,
  MonitoringRoute: MonitoringRoute,
  NotifikasiRoute: NotifikasiRoute,
  PengangkutanRoute: PengangkutanRoute,
  PengaturanRoute: PengaturanRoute,
  RiwayatRoute: RiwayatRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
